"""remove payments_this_month and revenue_this_month from dashboard_metrics

Revision ID: 6c9e738cef59
Revises: fc9e00de3dfc
Create Date: 2026-06-25 22:26:04.539888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c9e738cef59'
down_revision: Union[str, Sequence[str], None] = 'fc9e00de3dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard_metrics', 'revenue_this_month')
    op.drop_column('dashboard_metrics', 'payments_this_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_metrics', sa.Column('payments_this_month', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('dashboard_metrics', sa.Column('revenue_this_month', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False))
    # ### end Alembic commands ###
