"""add_dashboard_metrics_table

Revision ID: e2c2c5671e78
Revises: 5dc8882d8c63
Create Date: 2026-06-24 01:25:20.461887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c2c5671e78'
down_revision: Union[str, Sequence[str], None] = '5dc8882d8c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inactive_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unverified_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paid_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('canceled_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('monthly_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('yearly_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('approved_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_metrics')
    # ### end Alembic commands ###
