"""update_schema

Revision ID: edb75093d354
Revises: 
Create Date: 2026-06-26 13:29:38.855422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'edb75093d354'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('active_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('inactive_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('verified_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unverified_users', sa.Integer(), server_default='0', nullable=False),
    sa.Column('plans_distribution', sa.JSON(), nullable=True),
    sa.Column('total_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paid_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('canceled_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('monthly_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('yearly_payments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('published_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('pending_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('approved_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rejected_requests', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_billing_cycle'), 'payments', ['billing_cycle'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_plan_id'), 'payments', ['plan_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.alter_column('requests', 'service_type',
               existing_type=mysql.ENUM('operational_partnership', 'feasibility_study'),
               type_=sa.Enum('partnership', 'feasibility_study', name='service_type'),
               existing_nullable=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_is_published'), 'reviews', ['is_published'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.drop_index(op.f('ix_UserFile_file_id'), table_name='user_files')
    op.drop_index(op.f('ix_UserFile_request_id'), table_name='user_files')
    op.create_index(op.f('ix_user_files_file_id'), 'user_files', ['file_id'], unique=True)
    op.create_index(op.f('ix_user_files_request_id'), 'user_files', ['request_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_current_plan_id'), 'users', ['current_plan_id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_email_verified'), 'users', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_current_plan_id'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_user_files_request_id'), table_name='user_files')
    op.drop_index(op.f('ix_user_files_file_id'), table_name='user_files')
    op.create_index(op.f('ix_UserFile_request_id'), 'user_files', ['request_id'], unique=False)
    op.create_index(op.f('ix_UserFile_file_id'), 'user_files', ['file_id'], unique=True)
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_is_published'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.alter_column('requests', 'service_type',
               existing_type=sa.Enum('partnership', 'feasibility_study', name='service_type'),
               type_=mysql.ENUM('operational_partnership', 'feasibility_study'),
               existing_nullable=False)
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_plan_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_cycle'), table_name='payments')
    op.drop_table('dashboard_metrics')
    # ### end Alembic commands ###
