"""add user index

Revision ID: fc9e00de3dfc
Revises: e2c2c5671e78
Create Date: 2026-06-25 02:18:41.781241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc9e00de3dfc'
down_revision: Union[str, Sequence[str], None] = 'e2c2c5671e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_payments_month_stats'), table_name='payments')
    op.drop_index(op.f('idx_user_role_plan'), table_name='users')
    op.drop_index(op.f('idx_user_role_plan_id'), table_name='users')
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_email_verified'), 'users', ['is_email_verified'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_email_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.create_index(op.f('idx_user_role_plan_id'), 'users', ['role', 'current_plan_id', 'id'], unique=False)
    op.create_index(op.f('idx_user_role_plan'), 'users', ['role', 'current_plan_id'], unique=False)
    op.create_index(op.f('idx_payments_month_stats'), 'payments', ['created_at', 'status', 'amount'], unique=False)
    # ### end Alembic commands ###
